spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


    #optional
  flyway:
    enabled: true
    locations: classpath:/db/migration

app:
  ingestion:
    feed-url: https://vnexpress.net/rss/khoa-hoc-cong-nghe.rss